use_frameworks!
platform :ios, ‘8.0’

target ‘MVVM-RAC-2’ do

pod 'ReactiveCocoa', ‘2.5’
pod 'AFNetworking', '~> 3.1.0'
pod 'SVProgressHUD', '~> 2.0.3'
pod 'SDWebImage' , '3.7.3'
pod 'Masonry'
pod 'MJRefresh'
pod 'DZNEmptyDataSet', '~> 1.8.1'
pod 'Reachability', '~> 3.2'
pod 'MJExtension'

end